### ISSUE TITLE
filtering duplicates

### ISSUE THREAD

**Issue by yocontra** [deoxxa/combine-stream#2]
recordDuplicates in the README makes it seem like this feature exists but it does not. I can always pipe this to another stream that filters it so no problem but you might want to remove it from the docs

**Comment by yocontra** [comment]
Usage is here https://github.com/wearefractal/glob-stream/blob/master/index.js#L103

**Comment by hemanth** [comment]
@contra Willing to do a PR?

**Comment by yocontra** [comment]
@hemanth Don't have a ton of time and we actually don't need the feature anymore since we are using some custom stuff for negations now :/

**Comment by hemanth** [comment]
No problem, will resolve it. Thanks.
